<?php
session_start();
if (!is_file(__DIR__.'/config.php')) { header('Location: install.php'); exit; }
require __DIR__.'/config.php';
function db(){static $p;if($p instanceof PDO)return $p;$p=new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4',DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);return $p;}
function q($s,$a=[]){$x=db()->prepare($s);$x->execute($a);return $x;} function one($s,$a=[]){return q($s,$a)->fetch();} function all($s,$a=[]){return q($s,$a)->fetchAll();} function val($s,$a=[]){return q($s,$a)->fetchColumn();}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function now(){return time();} function me(){return (int)($_SESSION['uid']??0);} function needLogin(){if(!me()){header('Location: index.php');exit;}}
function flash($m,$t='ok'){$_SESSION['flash']=['m'=>$m,'t'=>$t];} function takeFlash(){$f=$_SESSION['flash']??null;unset($_SESSION['flash']);return $f;}
function tribes(){return [1=>'Roman',2=>'Teuton',3=>'Gaul'];}
function buildingDefs(){return [
15=>['name'=>'Main Building','base'=>[70,40,60,20],'req'=>[],'time'=>30],10=>['name'=>'Warehouse','base'=>[130,160,90,40],'req'=>[],'time'=>45],11=>['name'=>'Granary','base'=>[80,100,70,20],'req'=>[],'time'=>40],17=>['name'=>'Marketplace','base'=>[80,70,120,70],'req'=>[15=>3],'time'=>55],18=>['name'=>'Embassy','base'=>[220,160,90,40],'req'=>[15=>1],'time'=>70],19=>['name'=>'Barracks','base'=>[210,140,260,120],'req'=>[15=>3],'time'=>75],20=>['name'=>'Stable','base'=>[260,140,220,100],'req'=>[19=>3],'time'=>90],21=>['name'=>'Workshop','base'=>[460,510,600,320],'req'=>[15=>5],'time'=>120],22=>['name'=>'Academy','base'=>[220,160,90,40],'req'=>[15=>3],'time'=>80],23=>['name'=>'Smithy','base'=>[170,200,380,130],'req'=>[22=>3],'time'=>85],24=>['name'=>'Town Hall','base'=>[1250,1110,1260,600],'req'=>[15=>10],'time'=>180],25=>['name'=>'Residence','base'=>[580,460,350,180],'req'=>[15=>5],'time'=>120],26=>['name'=>'Palace','base'=>[550,800,750,250],'req'=>[15=>5],'time'=>150],27=>['name'=>'Rally Point','base'=>[110,160,90,70],'req'=>[],'time'=>55],28=>['name'=>'Wall','base'=>[160,100,210,50],'req'=>[],'time'=>60],29=>['name'=>'Cranny','base'=>[40,50,30,10],'req'=>[],'time'=>25],30=>['name'=>'Sawmill','base'=>[520,380,290,90],'req'=>[15=>5],'time'=>100],31=>['name'=>'Brickyard','base'=>[440,480,320,50],'req'=>[15=>5],'time'=>100],32=>['name'=>'Iron Foundry','base'=>[400,350,520,100],'req'=>[15=>5],'time'=>100],33=>['name'=>'Grain Mill','base'=>[500,440,380,0],'req'=>[15=>5],'time'=>100]];}
function unitDefs(){return [1=>['name'=>'Legionnaire','building'=>19,'c'=>[120,100,150,30],'time'=>35,'atk'=>40,'def'=>35],2=>['name'=>'Praetorian','building'=>19,'c'=>[100,130,160,70],'time'=>40,'atk'=>30,'def'=>65],11=>['name'=>'Clubswinger','building'=>19,'c'=>[95,75,40,0],'time'=>25,'atk'=>40,'def'=>20],21=>['name'=>'Phalanx','building'=>19,'c'=>[100,130,55,30],'time'=>30,'atk'=>15,'def'=>40]];}
function world(){static $w;if(!$w)$w=one('SELECT * FROM op_worlds WHERE id=1');return $w;}
function prod($v){$p=[30,30,30,20];foreach(all('SELECT type,level FROM op_fields WHERE village_id=?',[$v['id']]) as $f)$p[(int)$f['type']-1]+=30*pow(1.25,max(0,(int)$f['level']-1));$p[3]-=(int)$v['population']+(int)$v['crop_upkeep'];return $p;}
function sync($vid){$v=one('SELECT * FROM op_villages WHERE id=?',[$vid]);if(!$v)return;$t=now();$dt=max(0,$t-(int)$v['last_tick']);if($dt){$p=prod($v);$r=['wood'=>$p[0],'clay'=>$p[1],'iron'=>$p[2],'crop'=>$p[3]];$set=[];$a=[];foreach($r as $k=>$rate){$cap=$k==='crop'?$v['granary_cap']:$v['warehouse_cap'];$set[]="$k=?";$a[]=max(0,min($cap,(float)$v[$k]+$rate*$dt/3600));}$set[]='last_tick=?';$a[]=$t;$a[]=$vid;q('UPDATE op_villages SET '.implode(',',$set).' WHERE id=?',$a);}
 foreach(all('SELECT * FROM op_build_queue WHERE village_id=? AND finish_at<=? ORDER BY finish_at,id',[$vid,$t]) as $b){$table=(int)$b['action_type']?'op_fields':'op_buildings';q("UPDATE $table SET type=?,level=? WHERE village_id=? AND slot=?",[$b['building_type'],$b['level'],$vid,$b['slot']]);q('UPDATE op_villages SET population=population+1 WHERE id=?',[$vid]);q('DELETE FROM op_build_queue WHERE id=?',[$b['id']]);}}
function currentVillage(){needLogin();$v=one('SELECT * FROM op_villages WHERE id=? AND owner_id=?',[($_SESSION['village_id']??0),me()]);if(!$v)$v=one('SELECT * FROM op_villages WHERE owner_id=? ORDER BY id LIMIT 1',[me()]);if(!$v){session_destroy();header('Location: index.php');exit;}$_SESSION['village_id']=$v['id'];sync($v['id']);return one('SELECT * FROM op_villages WHERE id=?',[$v['id']]);}
function cost($type,$level){$d=buildingDefs()[$type]??null;if(!$d)return null;$f=pow(1.28,max(0,$level-1));return ['wood'=>(int)ceil($d['base'][0]*$f),'clay'=>(int)ceil($d['base'][1]*$f),'iron'=>(int)ceil($d['base'][2]*$f),'crop'=>(int)ceil($d['base'][3]*$f)];}
function queueBuild($v,$slot,$type,$level,$field){$c=cost($type,$level);foreach($c as $r=>$n)if($v[$r]<$n)throw new Exception('Niet genoeg grondstoffen.');if($field&&(int)val('SELECT COUNT(*) FROM op_build_queue WHERE village_id=? AND action_type=1',[$v['id']])>=2)throw new Exception('Veldenbouwqueue is vol.');if(!$field&&(int)val('SELECT COUNT(*) FROM op_build_queue WHERE village_id=? AND action_type=0',[$v['id']])>=1)throw new Exception('Gebouwenqueue is vol.');foreach($c as $r=>$n)q("UPDATE op_villages SET $r=$r-? WHERE id=?",[$n,$v['id']]);$last=(int)val('SELECT COALESCE(MAX(finish_at),0) FROM op_build_queue WHERE village_id=?',[$v['id']]);$start=max(now(),$last);$dur=(int)ceil((buildingDefs()[$type]['time']*pow(1.28,$level-1))/max(.1,(float)world()['speed']));q('INSERT INTO op_build_queue(village_id,slot,building_type,level,action_type,start_at,finish_at) VALUES(?,?,?,?,?,?,?)',[$v['id'],$slot,$type,$level,$field?1:0,$start,$start+$dur]);}
function logout(){session_destroy();header('Location: index.php');exit;}
