<?php
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }
if (!is_file(__DIR__.'/config.php')) { header('Location: install.php'); exit; }
require_once __DIR__.'/config.php';
function db(){static $p;if($p instanceof PDO)return $p;$p=new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4',DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);return $p;}
try { db()->query('SELECT 1 FROM op_worlds LIMIT 1'); } catch(Throwable $e) { if (basename($_SERVER['SCRIPT_NAME']??'')!=='install.php') { header('Location: install.php'); exit; } }
function q($s,$a=[]){$x=db()->prepare($s);$x->execute($a);return $x;} function one($s,$a=[]){return q($s,$a)->fetch();} function all($s,$a=[]){return q($s,$a)->fetchAll();} function val($s,$a=[]){return q($s,$a)->fetchColumn();}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function now(){return time();} function me(){return (int)($_SESSION['uid']??0);} function needLogin(){if(!me()){header('Location: auth.php');exit;}}
function flash($m,$t='ok'){$_SESSION['flash']=['m'=>$m,'t'=>$t];} function takeFlash(){$f=$_SESSION['flash']??null;unset($_SESSION['flash']);return $f;}
function tribes(){return [1=>'Romeinen',2=>'Germanen',3=>'Galliërs'];}
function buildingDefs(){return [
15=>['name'=>'Hoofdgebouw','base'=>[70,40,60,20],'req'=>[],'time'=>30],10=>['name'=>'Magazijn','base'=>[130,160,90,40],'req'=>[],'time'=>45],11=>['name'=>'Graanschuur','base'=>[80,100,70,20],'req'=>[],'time'=>40],17=>['name'=>'Marktplaats','base'=>[80,70,120,70],'req'=>[15=>3],'time'=>55],18=>['name'=>'Ambassade','base'=>[220,160,90,40],'req'=>[15=>1],'time'=>70],19=>['name'=>'Kazerne','base'=>[210,140,260,120],'req'=>[15=>3],'time'=>75],20=>['name'=>'Stal','base'=>[260,140,220,100],'req'=>[19=>3],'time'=>90],21=>['name'=>'Werkplaats','base'=>[460,510,600,320],'req'=>[15=>5],'time'=>120],22=>['name'=>'Academie','base'=>[220,160,90,40],'req'=>[15=>3],'time'=>80],23=>['name'=>'Smederij','base'=>[170,200,380,130],'req'=>[22=>3],'time'=>85],24=>['name'=>'Raadhuis','base'=>[1250,1110,1260,600],'req'=>[15=>10],'time'=>180],25=>['name'=>'Residentie','base'=>[580,460,350,180],'req'=>[15=>5],'time'=>120],26=>['name'=>'Paleis','base'=>[550,800,750,250],'req'=>[15=>5],'time'=>150],27=>['name'=>'Verzamelplaats','base'=>[110,160,90,70],'req'=>[],'time'=>55],28=>['name'=>'Muur','base'=>[160,100,210,50],'req'=>[],'time'=>60],29=>['name'=>'Schuilplaats','base'=>[40,50,30,10],'req'=>[],'time'=>25],30=>['name'=>'Houthakker','base'=>[520,380,290,90],'req'=>[15=>5],'time'=>100],31=>['name'=>'Steenbakkerij','base'=>[440,480,320,50],'req'=>[15=>5],'time'=>100],32=>['name'=>'IJzergieterij','base'=>[400,350,520,100],'req'=>[15=>5],'time'=>100],33=>['name'=>'Graanmolen','base'=>[500,440,380,0],'req'=>[15=>5],'time'=>100]];}
function unitDefs(){return [1=>['name'=>'Legionair','building'=>19,'c'=>[120,100,150,30],'time'=>35,'atk'=>40,'def'=>35],2=>['name'=>'Pretoriaan','building'=>19,'c'=>[100,130,160,70],'time'=>40,'atk'=>30,'def'=>65],11=>['name'=>'Knuppelvechter','building'=>19,'c'=>[95,75,40,0],'time'=>25,'atk'=>40,'def'=>20],21=>['name'=>'Phalanx','building'=>19,'c'=>[100,130,55,30],'time'=>30,'atk'=>15,'def'=>40]];}
function world(){static $w;if(!$w)$w=one('SELECT * FROM op_worlds WHERE id=1');return $w;}
function prod($v){$p=[30,30,30,20];foreach(all('SELECT type,level FROM op_fields WHERE village_id=?',[$v['id']]) as $f){$i=(int)$f['type']-1;if($i>=0&&$i<4&&(int)$f['level']>0)$p[$i]+=30*pow(1.25,(int)$f['level']-1);}$p[3]-=(int)$v['population']+(int)$v['crop_upkeep'];return $p;}
function sync($vid){$v=one('SELECT * FROM op_villages WHERE id=?',[$vid]);if(!$v)return;$t=now();$dt=max(0,$t-(int)$v['last_tick']);if($dt){$p=prod($v);$r=['wood'=>$p[0],'clay'=>$p[1],'iron'=>$p[2],'crop'=>$p[3]];$set=[];$a=[];foreach($r as $k=>$rate){$cap=$k==='crop'?$v['granary_cap']:$v['warehouse_cap'];$set[]="$k=?";$a[]=max(0,min($cap,(float)$v[$k]+$rate*$dt/3600));}$set[]='last_tick=?';$a[]=$t;$a[]=$vid;q('UPDATE op_villages SET '.implode(',',$set).' WHERE id=?',$a);}
foreach(all('SELECT * FROM op_build_queue WHERE village_id=? AND finish_at<=? ORDER BY finish_at,id',[$vid,$t]) as $b){$table=(int)$b['action_type']?'op_fields':'op_buildings';q("UPDATE $table SET type=?,level=? WHERE village_id=? AND slot=?",[$b['building_type'],$b['level'],$vid,$b['slot']]);q('UPDATE op_villages SET population=population+1 WHERE id=?',[$vid]);q('DELETE FROM op_build_queue WHERE id=?',[$b['id']]);}
foreach(all('SELECT type,level FROM op_buildings WHERE village_id=?',[$vid]) as $b){if((int)$b['type']===10){$cap=800+500*(int)$b['level'];q('UPDATE op_villages SET warehouse_cap=? WHERE id=?',[$cap,$vid]);}if((int)$b['type']===11){$cap=800+500*(int)$b['level'];q('UPDATE op_villages SET granary_cap=? WHERE id=?',[$cap,$vid]);}}
}
function currentVillage(){needLogin();$v=one('SELECT * FROM op_villages WHERE id=? AND owner_id=?',[($_SESSION['village_id']??0),me()]);if(!$v)$v=one('SELECT * FROM op_villages WHERE owner_id=? ORDER BY id LIMIT 1',[me()]);if(!$v){session_destroy();header('Location: auth.php');exit;}$_SESSION['village_id']=$v['id'];sync($v['id']);return one('SELECT * FROM op_villages WHERE id=?',[$v['id']]);}
function cost($type,$level){$fieldBase=[1=>[60,25,20,15],2=>[80,40,80,20],3=>[100,80,30,60],4=>[70,90,70,20]];if(isset($fieldBase[$type])){$base=$fieldBase[$type];$f=pow(1.67,max(0,$level-1));return ['wood'=>(int)ceil($base[0]*$f),'clay'=>(int)ceil($base[1]*$f),'iron'=>(int)ceil($base[2]*$f),'crop'=>(int)ceil($base[3]*$f)];}$d=buildingDefs()[$type]??null;if(!$d)throw new RuntimeException('Onbekend gebouwtype.');$f=pow(1.28,max(0,$level-1));return ['wood'=>(int)ceil($d['base'][0]*$f),'clay'=>(int)ceil($d['base'][1]*$f),'iron'=>(int)ceil($d['base'][2]*$f),'crop'=>(int)ceil($d['base'][3]*$f)];}
function queueBuild($v,$slot,$type,$level,$field){$c=cost($type,$level);foreach($c as $r=>$n)if((float)$v[$r]<$n)throw new RuntimeException('Niet genoeg grondstoffen.');$action=$field?1:0;$max=$field?2:1;if((int)val('SELECT COUNT(*) FROM op_build_queue WHERE village_id=? AND action_type=?',[$v['id'],$action])>=$max)throw new RuntimeException('De bouwqueue is vol.');$table=$field?'op_fields':'op_buildings';$target=one("SELECT * FROM $table WHERE village_id=? AND slot=?",[$v['id'],$slot]);if(!$target)throw new RuntimeException('Bouwplaats bestaat niet.');if($field&&((int)$target['level']!==$level-1))throw new RuntimeException('Grondstoffenveld is al gewijzigd.');if(!$field&&$level===1&&(int)$target['type']!==0)throw new RuntimeException('Bouwplaats is niet vrij.');foreach($c as $r=>$n)q("UPDATE op_villages SET $r=$r-? WHERE id=?",[$n,$v['id']]);$last=(int)val('SELECT COALESCE(MAX(finish_at),0) FROM op_build_queue WHERE village_id=? AND action_type=?',[$v['id'],$action]);$start=max(now(),$last);$dur=(int)ceil(((buildingDefs()[$type]['time']??35)*pow(1.28,max(0,$level-1)))/max(.1,(float)world()['speed']));q('INSERT INTO op_build_queue(village_id,slot,building_type,level,action_type,start_at,finish_at) VALUES(?,?,?,?,?,?,?)',[$v['id'],$slot,$type,$level,$action,$start,$start+$dur]);}
function logout(){$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',(time()-42000),$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();header('Location: auth.php');exit;}
