<?php
require __DIR__.'/bootstrap.php';needLogin();$v=currentVillage();$p=one('SELECT * FROM op_players WHERE id=?',[me()]);$defs=buildingDefs();$units=unitDefs();$page=$_GET['page']??'village';$names=['wood'=>'Hout','clay'=>'Klei','iron'=>'IJzer','crop'=>'Graan'];
if(isset($_GET['logout']))logout();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$a=$_POST['action']??'';
if($a==='build_field'){$s=(int)$_POST['slot'];$f=one('SELECT * FROM op_fields WHERE village_id=? AND slot=?',[$v['id'],$s]);if(!$f)throw new Exception('Veld bestaat niet.');$lvl=(int)$f['level']+1;if($lvl>10)throw new Exception('Maximaal level 10.');queueBuild($v,$s,(int)$f['type'],$lvl,true);flash('Veldupgrade gestart.');}
elseif($a==='build'){$s=(int)$_POST['slot'];$type=(int)$_POST['type'];$b=one('SELECT * FROM op_buildings WHERE village_id=? AND slot=?',[$v['id'],$s]);if(!$b||$b['type']!=0)throw new Exception('Bouwplaats is niet vrij.');if(!isset($defs[$type]))throw new Exception('Ongeldig gebouw.');foreach($defs[$type]['req'] as $rt=>$rl){$have=(int)val('SELECT COALESCE(MAX(level),0) FROM op_buildings WHERE village_id=? AND type=?',[$v['id'],$rt]);if($have<$rl)throw new Exception('Vereiste gebouw ontbreekt.');}queueBuild($v,$s,$type,1,false);flash('Gebouwbouw gestart.');}
elseif($a==='upgrade'){$s=(int)$_POST['slot'];$b=one('SELECT * FROM op_buildings WHERE village_id=? AND slot=?',[$v['id'],$s]);if(!$b||$b['type']==0)throw new Exception('Geen gebouw op deze plek.');$lvl=(int)$b['level']+1;if($lvl>20)throw new Exception('Maximaal level 20.');queueBuild($v,$s,(int)$b['type'],$lvl,false);flash('Upgrade gestart.');}
elseif($a==='train'){$t=(int)$_POST['type'];$n=max(1,min(50,(int)$_POST['amount']));$u=$units[$t]??null;if(!$u)throw new Exception('Eenheid onbekend.');$bl=(int)val('SELECT COALESCE(MAX(level),0) FROM op_buildings WHERE village_id=? AND type=?',[$v['id'],$u['building']]);if($bl<1)throw new Exception('Bouw eerst de Barracks.');foreach(['wood','clay','iron','crop'] as $i=>$r)if($v[$r]<$u['c'][$i])throw new Exception('Niet genoeg grondstoffen.');foreach(['wood','clay','iron','crop'] as $i=>$r)q("UPDATE op_villages SET $r=$r-? WHERE id=?",[$u['c'][$i]*$n,$v['id']]);q('INSERT INTO op_units(village_id,unit_type,amount) VALUES(?,?,?) ON DUPLICATE KEY UPDATE amount=amount+VALUES(amount)',[$v['id'],$t,$n]);flash($n.' '.$u['name'].' getraind.');}
elseif($a==='market'){$g=(int)$_POST['give'];$w=(int)$_POST['want'];$n=max(1,(int)$_POST['amount']);$wn=max(1,(int)$_POST['want_amount']);$rs=['wood','clay','iron','crop'];if(!isset($rs[$g],$rs[$w]))throw new Exception('Ongeldige grondstof.');$gr=$rs[$g];if($v[$gr]<$n)throw new Exception('Niet genoeg grondstoffen.');q("UPDATE op_villages SET $gr=$gr-? WHERE id=?",[$n,$v['id']]);q('INSERT INTO op_market(seller_id,village_id,give_type,give_amount,want_type,want_amount,created_at) VALUES(?,?,?,?,?,?,?)',[me(),$v['id'],$g,$n,$w,$wn,now()]);flash('Marktaanbod geplaatst.');}
elseif($a==='hero'){$n=rand(150,400);q('UPDATE op_villages SET wood=LEAST(warehouse_cap,wood+?),clay=LEAST(warehouse_cap,clay+?),iron=LEAST(warehouse_cap,iron+?),crop=LEAST(granary_cap,crop+?) WHERE id=?',[$n,$n,$n,$n,$v['id']]);q('UPDATE op_hero SET xp=xp+? WHERE player_id=?',[$n,me()]);flash('Held terug: +'.$n.' van elke grondstof.');}
elseif($a==='quest'){q('UPDATE op_quests SET status=1,progress=1 WHERE player_id=? AND quest_key=?',[me(),'first_field']);q('UPDATE op_villages SET wood=wood+250,clay=clay+250,iron=iron+250,crop=LEAST(granary_cap,crop+250) WHERE id=?',[$v['id']]);flash('Opdrachtbeloning ontvangen.');}
elseif($a==='kingdom'){$name=trim($_POST['name']??'Mijn Koninkrijk');if($name==='')throw new Exception('Naam ontbreekt.');$tag=strtoupper(substr(preg_replace('/[^A-Za-z]/','',$name),0,4))?:'KING';q('INSERT INTO op_kingdoms(name,tag,king_id,created_at) VALUES(?,?,?,?)',[$name,$tag,me(),now()]);$kid=db()->lastInsertId();q('UPDATE op_players SET kingdom_id=? WHERE id=?',[$kid,me()]);flash('Koninkrijk aangemaakt.');}
elseif($a==='rename'){$n=trim($_POST['name']??'');if($n==='')throw new Exception('Naam ontbreekt.');q('UPDATE op_villages SET name=? WHERE id=? AND owner_id=?',[$n,$v['id'],me()]);flash('Dorp hernoemd.');}
} catch(Throwable $e){flash($e->getMessage(),'err');}$v=currentVillage();$p=one('SELECT * FROM op_players WHERE id=?',[me()]);}
$f=takeFlash();$fields=all('SELECT * FROM op_fields WHERE village_id=? ORDER BY slot',[$v['id']]);$buildings=all('SELECT * FROM op_buildings WHERE village_id=? ORDER BY slot',[$v['id']]);$queue=all('SELECT * FROM op_build_queue WHERE village_id=? ORDER BY finish_at',[$v['id']]);$rate=prod($v);$reports=all('SELECT * FROM op_reports WHERE owner_id=? ORDER BY id DESC LIMIT 20',[me()]);$myunits=all('SELECT * FROM op_units WHERE village_id=? AND amount>0 ORDER BY unit_type',[$v['id']]);
function bn($t){$d=buildingDefs();return $d[$t]['name']??'Vrije bouwplaats';}
function tile($x,$y){return one('SELECT v.name,p.username FROM op_villages v JOIN op_players p ON p.id=v.owner_id WHERE v.x=? AND v.y=?',[$x,$y]);}
?><!doctype html><html><head><meta charset="utf-8"><title><?=e($v['name'])?> - Kingdoms</title><style>
body{margin:0;background:#d8c89f;color:#2d281f;font:14px Arial}.top{height:66px;background:linear-gradient(#44523d,#202a20);display:flex;align-items:center;gap:8px;padding:0 14px;color:#fff;box-shadow:0 2px 8px #000}.logo{font:27px Georgia;color:#dfbb70;margin-right:8px}.r{padding:6px 10px;background:#121a13;border:1px solid #66725d;border-radius:4px;min-width:100px}.r b{display:block;color:#e7c77d}.topnav{margin-left:auto}.topnav a,.btn{display:inline-block;padding:8px 10px;margin:2px;background:#86642f;color:#fff;text-decoration:none;border:1px solid #c29b59;border-radius:4px}.layout{max-width:1280px;margin:16px auto;display:grid;grid-template-columns:180px 1fr 230px;gap:12px}.panel,.card{background:#f2e4bf;border:1px solid #9b845a;border-radius:6px;box-shadow:0 2px 10px #0002;padding:12px}.menu a{display:block;padding:10px;color:#302a20;text-decoration:none;border-bottom:1px solid #ccb98a}.menu a:hover{background:#e3d1a8}.banner{background:linear-gradient(#69755b,#384635);color:#fff;padding:16px;border-radius:6px;border:1px solid #374232}.banner h1{font:26px Georgia;margin:0 0 5px}.flash{padding:10px;margin:8px 0;border-radius:5px}.ok{background:#d6e9cf}.err{background:#efd0c9}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.slot{background:#dfd0a8;border:1px solid #a18d65;border-radius:5px;padding:8px;min-height:90px}.empty{background:#cdbd93}.slot button,.slot select,.slot input{margin-top:6px;padding:6px}.slot button,.submit{background:#89672f;color:#fff;border:1px solid #60451f;border-radius:4px}.table{width:100%;border-collapse:collapse}.table td,.table th{padding:7px;border-bottom:1px solid #c8b88c;text-align:left}.map{display:grid;grid-template-columns:repeat(9,1fr);gap:3px;background:#7f9064;padding:7px}.tile{aspect-ratio:1;background:#9eac7e;border:1px solid #687756;text-align:center;font-size:10px;padding-top:13px}.tile.mine{background:#81683d;color:#fff}.small{font-size:12px;color:#6d644f}@media(max-width:950px){.layout{grid-template-columns:1fr}.menu{display:flex;overflow:auto}.menu a{white-space:nowrap}.topnav{display:none}.grid{grid-template-columns:repeat(2,1fr)}} </style></head><body>
<div class="top"><div class="logo">Kingdoms</div><div class="r"><b>Hout</b><?=number_format($v['wood'],0)?>/<?=number_format($v['warehouse_cap'])?></div><div class="r"><b>Klei</b><?=number_format($v['clay'],0)?>/<?=number_format($v['warehouse_cap'])?></div><div class="r"><b>IJzer</b><?=number_format($v['iron'],0)?>/<?=number_format($v['warehouse_cap'])?></div><div class="r"><b>Graan</b><?=number_format($v['crop'],0)?>/<?=number_format($v['granary_cap'])?></div><div class="topnav"><a href="game.php">Dorp</a><a href="game.php?page=map">Kaart</a><a href="game.php?page=ranking">Ranking</a><a href="game.php?logout=1">Uitloggen</a></div></div>
<div class="layout"><aside class="panel menu"><a href="game.php">🏰 Dorp</a><a href="game.php?page=fields">🌲 Velden</a><a href="game.php?page=buildings">🏛 Gebouwen</a><a href="game.php?page=troops">⚔ Leger</a><a href="game.php?page=market">⚖ Handel</a><a href="game.php?page=map">🗺 Kaart</a><a href="game.php?page=kingdom">👑 Koninkrijk</a><a href="game.php?page=hero">🛡 Held</a><a href="game.php?page=quests">📜 Opdrachten</a><a href="game.php?page=reports">✉ Rapporten</a><a href="game.php?page=ranking">🏆 Ranking</a></aside><main>
<div class="banner"><h1><?=e($v['name'])?></h1><?=e($p['username'])?> · <?=e(tribes()[$p['tribe']])?> · Bevolking <?=$v['population']?><div class="small" style="color:#ddd">Per uur: 🪵<?=number_format($rate[0],0)?> 🧱<?=number_format($rate[1],0)?> ⛓<?=number_format($rate[2],0)?> 🌾<?=number_format($rate[3],0)?></div></div>
<?php if($f):?><div class="flash <?=$f['t']==='err'?'err':'ok'?>"><?=e($f['m'])?></div><?php endif;?>
<?php if($page==='village'||$page==='fields'):?><div class="card"><h2>Grondstoffenvelden</h2><div class="grid"><?php foreach($fields as $x):$nn=[1=>'Houtvester',2=>'Kleigroeve',3=>'Ijzermijn',4=>'Graanveld'][$x['type']];?><div class="slot"><b>Veld <?=$x['slot']?></b><br><?=$nn?><br>Level <?=$x['level']?>/10<form method="post"><input type="hidden" name="action" value="build_field"><input type="hidden" name="slot" value="<?=$x['slot']?>"><button class="submit">Upgrade</button></form></div><?php endforeach;?></div></div><div class="card"><h2>Dorpscentrum</h2><div class="grid"><?php foreach($buildings as $b):?><div class="slot <?=!$b['type']?'empty':''?>"><b>Slot <?=$b['slot']?></b><br><?=e(bn($b['type']))?><?php if($b['type']):?><br>Level <?=$b['level']?><form method="post"><input type="hidden" name="action" value="upgrade"><input type="hidden" name="slot" value="<?=$b['slot']?>"><button class="submit">Upgrade</button></form><?php else:?><form method="post"><input type="hidden" name="action" value="build"><input type="hidden" name="slot" value="<?=$b['slot']?>"><select name="type"><?php foreach($defs as $t=>$d):?><option value="<?=$t?>"><?=e($d['name'])?></option><?php endforeach;?></select><button class="submit">Bouw</button></form><?php endif;?></div><?php endforeach;?></div></div>
<?php elseif($page==='buildings'):?><div class="card"><h2>Gebouwen</h2><table class="table"><tr><th>Gebouw</th><th>Kosten level 1</th><th>Vereiste</th></tr><?php foreach($defs as $t=>$d):?><tr><td><?=e($d['name'])?></td><td>🪵<?=$d['base'][0]?> 🧱<?=$d['base'][1]?> ⛓<?=$d['base'][2]?> 🌾<?=$d['base'][3]?></td><td><?php foreach($d['req'] as $rt=>$rl)echo e(bn($rt)).' '.$rl.' ';?></td></tr><?php endforeach;?></table></div>
<?php elseif($page==='troops'):?><div class="card"><h2>Leger</h2><?php foreach($units as $t=>$u):?><div class="slot" style="display:inline-block;width:44%;margin:5px"><b><?=e($u['name'])?></b><br>ATK <?=$u['atk']?> · DEF <?=$u['def']?><br>🪵<?=$u['c'][0]?> 🧱<?=$u['c'][1]?> ⛓<?=$u['c'][2]?> 🌾<?=$u['c'][3]?><form method="post"><input type="hidden" name="action" value="train"><input type="hidden" name="type" value="<?=$t?>"><input name="amount" type="number" min="1" max="50" value="1"><button class="submit">Train</button></form></div><?php endforeach;?><h3>Troepen in dorp</h3><?php foreach($myunits as $u):?><p><?=e($units[$u['unit_type']]['name']??'Eenheid')?>: <?=$u['amount']?></p><?php endforeach;?></div>
<?php elseif($page==='market'):?><div class="card"><h2>Handel</h2><form method="post"><input type="hidden" name="action" value="market"><select name="give"><option value="0">Hout</option><option value="1">Klei</option><option value="2">IJzer</option><option value="3">Graan</option></select><input name="amount" type="number" value="100" min="1"><select name="want"><option value="0">Hout</option><option value="1">Klei</option><option value="2">IJzer</option><option value="3">Graan</option></select><input name="want_amount" type="number" value="100" min="1"><button class="submit">Aanbod plaatsen</button></form><hr><?php foreach(all('SELECT m.*,p.username FROM op_market m JOIN op_players p ON p.id=m.seller_id ORDER BY m.id DESC LIMIT 20') as $m):?><p><?=e($m['username'])?> biedt <?=$m['give_amount']?> van resource <?=$m['give_type']?> voor <?=$m['want_amount']?> van resource <?=$m['want_type']?></p><?php endforeach;?></div>
<?php elseif($page==='map'):?><div class="card"><h2>Wereldkaart</h2><div class="map"><?php for($yy=-4;$yy<=4;$yy++):for($xx=-4;$xx<=4;$xx++):$tx=$v['x']+$xx;$ty=$v['y']+$yy;$z=tile($tx,$ty);?><div class="tile <?=$z?'mine':''?>"><?php if($z):?>🏰<br><?=e(substr($z['name'],0,9))?><?php else:?><?=$tx?>|<?=$ty?><?php endif;?></div><?php endfor;endfor;?></div></div>
<?php elseif($page==='kingdom'):?><div class="card"><h2>Koninkrijk</h2><?php $k=$p['kingdom_id']?one('SELECT * FROM op_kingdoms WHERE id=?',[$p['kingdom_id']]):null;if(!$k):?><form method="post"><input type="hidden" name="action" value="kingdom"><input name="name" value="Mijn Koninkrijk"><button class="submit">Koninkrijk stichten</button></form><?php else:?><h3><?=e($k['name'])?> [<?=e($k['tag'])?>]</h3><p>VP: <?=$k['victory_points']?> · Schatten: <?=$k['treasures']?></p><?php endif;?></div>
<?php elseif($page==='hero'):?><div class="card"><h2>Held</h2><?php $h=one('SELECT * FROM op_hero WHERE player_id=?',[me()]);?><p>Level <?=$h['level']?> · XP <?=$h['xp']?> · Kracht <?=$h['strength']?> · Gezondheid <?=$h['health']?>%</p><form method="post"><input type="hidden" name="action" value="hero"><button class="submit">Avontuur starten</button></form></div>
<?php elseif($page==='quests'):?><div class="card"><h2>Opdracht</h2><?php $qst=one('SELECT * FROM op_quests WHERE player_id=? AND quest_key=?',[me(),'first_field']);?><h3>Eerste ontwikkeling</h3><p>Upgrade een grondstoffenveld.</p><?php if(!$qst['status']):?><form method="post"><input type="hidden" name="action" value="quest"><button class="submit">Beloning ophalen</button></form><?php else:?><b>Voltooid ✓</b><?php endif;?></div>
<?php elseif($page==='reports'):?><div class="card"><h2>Rapporten</h2><?php foreach($reports as $r):?><div class="slot"><b><?=e($r['title'])?></b><p><?=e($r['body'])?></p></div><?php endforeach;?></div>
<?php elseif($page==='ranking'):?><div class="card"><h2>Ranking</h2><table class="table"><tr><th>#</th><th>Speler</th><th>Pop</th><th>Stam</th></tr><?php $rr=all('SELECT p.username,p.tribe,COALESCE(SUM(v.population),0) pop FROM op_players p LEFT JOIN op_villages v ON v.owner_id=p.id GROUP BY p.id ORDER BY pop DESC,p.id LIMIT 50');$i=1;foreach($rr as $r):?><tr><td><?=$i++?></td><td><?=e($r['username'])?></td><td><?=$r['pop']?></td><td><?=e(tribes()[$r['tribe']]??'')?></td></tr><?php endforeach;?></table></div><?php endif;?>
<?php if($queue):?><div class="card"><b>Bouwqueue</b><?php foreach($queue as $q):?><div><?=e(bn($q['building_type']))?> level <?=$q['level']?> — klaar <?=date('H:i:s',$q['finish_at'])?></div><?php endforeach;?></div><?php endif;?></main>
<aside class="panel"><h3>Account</h3><b><?=e($p['username'])?></b><p><?=e(tribes()[$p['tribe']])?><br>Goud: <?=$p['gold']?><br>Zilver: <?=$p['silver']?><br>CP: <?=$p['culture_points']?></p><h3>Dorp</h3><form method="post"><input type="hidden" name="action" value="rename"><input name="name" value="<?=e($v['name'])?>"><button class="submit">Naam wijzigen</button></form><p><a class="btn" href="game.php?page=fields">Velden</a><a class="btn" href="game.php?page=buildings">Gebouwen</a></p></aside></div></body></html>